### PR TITLE
Add liveness and readiness probes

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees PTAL

**Comment by bparees** [comment]
/articles only works when the DB is up?

**Comment by mfojtik** [comment]
@bparees yep, for non-db i'm checking /

**Comment by mfojtik** [comment]
@bparees scratch that... ETOOMANYEXAMPLES today... rails does not have non-db template and yes, /articles will work only with db... I'm testing every framework manually to confirm it works by scaling down the db and watching it fail :)

**Comment by bparees** [comment]
@mfojtik :+1:

**Pull request merged**
