### PR TITLE
Update ffi gem to 1.15.1.

### PR DESCRIPTION
**Pull request by jackorp**
The FFI gem 1.15.0 is missing a flag for pthread_atfork.
Due to that we observe `undefined symbol: pthread_atfork`
fail when trying to use the gem with Ruby 2.6.

FFI gem 1.15.1 fixes this by adding the -pthread option.

WIP status because I am unable to test it locally.

This was prompted by https://github.com/sclorg/s2i-ruby-container/issues/399

### CODE REVIEW

**Comment by pvalena** [comment]
Please for refreshing the dependencies, please check: 

- https://github.com/pvalena/rails-ex/blob/scripts/refresh_lock.sh
- https://github.com/pvalena/rails-ex/blob/scripts/test_ubi.sh
- (both use https://github.com/pvalena/rails-ex/blob/scripts/test_cont.sh)

(rebase WIP: https://github.com/pvalena/rails-ex/pull/4)

**Comment by pvalena** [comment]
(IOW, please don't modify Gemfile.lock manually, and instead make the changes in Gemfile)

**Comment by pvalena** [comment]
**EDIT:*** Or maybe it lives in `sclorg` repo?

https://github.com/sclorg/rails-ex/tree/scripts

*Ideally,those would be in sync, sorry - therefore the PR*

**Comment by pvalena** [comment]
@jackorp docs: #151

**Comment by pvalena** [comment]
Thanks for refreshing! Should I test or does it work across all containers?

**Comment by jackorp** [comment]
> Thanks for refreshing! Should I test or does it work across all containers?

it seems to work OK, but if you could test it as well I'd appreciate that.

**Comment by pvalena** [comment]
> > Thanks for refreshing! Should I test or does it work across all containers?
> 
> it seems to work OK, but if you could test it as well I'd appreciate that.

Works for me across  all containers. Let's find out whether it works in s2i-ruby-c. as well ;) in the linked PR [after merging].

Test log: https://gist.github.com/d63337022889a27f325c57b183ff39ff

_ _ _ _

I'm trying `./refresh_lock.sh` (scripts branch)  just to be sure I don't get different results (I did have some WIP refresh, and got different versions).

**Comment by pvalena** [comment]
All good.

**Pull request merged**
