### PR TITLE
Standardize templates across examples

### PR DESCRIPTION
**Pull request by rhcarvalho**
Changing Django, Rails and Node.js examples.
Tested all examples/templates with creating a project for each, deploying and curl'ing.

@bparees PTAL

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@ewolinetz @sspeiche PTAL

**Comment by ewolinetz** [comment]
@rhcarvalho Do we want to have a default value for CONTEXT_DIR?

**Comment by rhcarvalho** [comment]
@ewolinetz the CONTEXT_DIR there is just informational. For our examples it should be empty, since our apps are in the root of their repos.

**Comment by bparees** [comment]
lgtm.

**Pull request merged**
