### PR TITLE
Bump the postgresql max connections to 100

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@rhcarvalho / @bparees PTAL

**Comment by rhcarvalho** [comment]
Why raise it?

**Comment by mfojtik** [comment]
@rhcarvalho Eric was doing some ab perf tests against the app and he hit the connections limit. The 100 is default value for postgresql and I see no reason to change that default.

**Comment by rhcarvalho** [comment]
We have 100 as the default in v2 as well, let's go for it! LGTM

**Pull request merged**
