### PR TITLE
Make rails-ex work with Ruby 3.3

### PR DESCRIPTION
**Pull request by pvalena**
I have managed to make it work with Ruby 3.3!

It works with all the other Ruby versions as well. Test log: 
https://gist.github.com/pvalena/6834136128fb4fb131da6d779416831d

Ruby 3.3 PR & logs:: https://github.com/sclorg/s2i-ruby-container/pull/507

### CODE REVIEW

**Comment by pvalena** [comment]
@jackorp PTAL.

**Comment by phracek** [comment]
@pvalena Will this change work also with the older ruby versions? If not what about to branch it?

**Comment by pvalena** [comment]
@phracek 
Yes, it works with **ALL** Ruby versions we have additionally to Ruby 3.3. No branching needed. Test logs proving that are in the [initial comment](https://github.com/sclorg/rails-ex/pull/165#issue-2086874727).

**Comment by jackorp** [comment]
@phracek The app should be OK as long as this set of dependencies is not tested on RHEL 7 (or RHEL 7 based containers for that matter) due to the incompatibility between the system postgresql version and the newer rubygem-pg database connector. If we still need/want to test against RHEL 7, only then I think branching out is needed.

**Comment by pvalena** [comment]
Can we merge this? Is anything else needed from my side?

**Comment by jackorp** [comment]
@pvalena testing the rails-ex with RHEL 7 is still expected and required. Your current gemfile will not work because rubygem-pg with version this high does not work with Postgres (or probably even compile) that is default on RHEL 7. That is why a new branch is needed and we cannot do this refresh on master.

**Comment by pvalena** [comment]
Oh, and can't we create a branch for RHEL-7 instead?

**Comment by jackorp** [comment]
If I recall correctly my last discussion with @phracek about this, the preferred way is to have a branch for 3.3 onward rather than the inverse.

**Comment by pvalena** [comment]
Ok then - or can't version/tag suffice? Do we expect any updates will be needed for RHEL-7 further on?
If not, can you create the branch and I'll move the PR target there.

**Pull request closed without merging**
