### PR TITLE
Renamed front end route variable name and default value

### PR DESCRIPTION
**Pull request by ewolinetz**

### CODE REVIEW

**Comment by ewolinetz** [comment]
@bparees PTAL

**Comment by mfojtik** [comment]
please add this parameter as env var for frontend container

**Comment by bparees** [comment]
@mfojtik is the app going to use it for something?

**Comment by bparees** [comment]
lgtm, we can add @mfojtik's suggestion in a follow on if it's important, i'd like to stop iterating on these templates if we can :)

**Comment by ewolinetz** [comment]
@bparees @mfojtik i actually added that suggestion in.. so we shouldn't need to address it in a later PR

**Pull request merged**
