### PR TITLE
add default memory limit to deployments

### PR DESCRIPTION
**Pull request by gabemontero**
@bparees PTAL

### CODE REVIEW

**Comment by mfojtik** [comment]
@gabemontero I think 128Mib for rails is pretty low :-)

**Comment by gabemontero** [comment]
@bparees @mfojtik - so @mfojtik pointed me to redmine.  I pulled down the image from docker.io and its basic startup unfettered does surpass 128 MiB.  And after some web searching, there is certainly a lot of chatter around it being a memory hog.

There were many hits ... I found this one the most concise and definitive, with the assumption that definitiveness implies correctness :-) :  http://stackoverflow.com/questions/4964533/reducing-redmines-memory-usage-low-hanging-fruit

It points to 512 MiB (including database).

So a couple of thoughts:
- certainly users can tweak the mem limit when instantiating the template 
- redmine users seem to be very accustomed to having to deal with capacity planning and memory tuning
- if a user were to clone/modify our rail template to pull in redmine, it seems reasonable they would see the memory limit and tune accordingly

That said, and with the online beta in mind when saying this, pending further suggestions/insgight, I'm going to bump to 512 MiB (even though the above link included database in that number).  It is still not high end for sure (some links pointed to growth in the GBs), but feels like a good middle of the road compromise.

And thanks @mfojtik  :-)

**Comment by gabemontero** [comment]
update pushed

**Comment by bparees** [comment]
lgtm

**Pull request merged**
