### PR TITLE
Update templates to API v1

### PR DESCRIPTION
**Pull request by rhcarvalho**
Update to v1 and cleaning up of needless bits. Tested both templates with

```
oc process -f path/to/rails-ex/openshift/templates/rails[-postgresql].json | oc create -f -
```

and 

```
curl service-ip:port
```

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees @mfojtik PTAL

**Comment by bparees** [comment]
can we make the source uri parameter name consistent across the templates?

**Comment by sspeiche** [comment]
I have that in the works, I upgraded my local demo/test env but broken. I
can just do it, was hoping to test it all the way through.

**Comment by rhcarvalho** [comment]
@sspeiche @bparees I'm making those consistency changes as a separate step

**Comment by bparees** [comment]
ok.  lgtm.

**Pull request merged**
