### PR TITLE
Add RAILS_LOG_TO_STDOUT env var to template

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by coreydaley** [comment]
@bparees ptal

**Comment by luciddreamz** [comment]
This change is fine if you really want it, but if you revert https://github.com/openshift/rails-ex/pull/102/files then logging will not work for users deploying from the template that is currently installed on all OpenShift clusters. 

I thought the point of these examples was that we took the normal framework configuration and modified it with the changes necessary to run properly on OpenShift. Why would you add a configuration flag into the configuration to break logging just because the upstream config file has the flag?

**Comment by luciddreamz** [comment]
Changing config to match upstream rather than carefully preserving our customizations appears to be what caused this issue as well: https://github.com/openshift/rails-ex/commit/881188e664287f84ebe6a0491127bd7e9df6b9bc#diff-1d98f0039bbc6df92adee882ed99d993

**Comment by bparees** [comment]
> This change is fine if you really want it, but if you revert https://github.com/openshift/rails-ex/pull/102/files then logging will not work for users deploying from the template that is currently installed on all OpenShift clusters.

we're not going to revert the other change.  This is more belt/suspenders in case the if-statement gets reverted back in in the future.

However @coreydaley did note that w/ the app code being what it is, this env var can't actually *disable* the logging which may cause confusion for users.  I guess i'm willing to explain that to them when/if the time comes.

**Comment by luciddreamz** [comment]
@bparees @coreydaley Ok well by that logic you should be adding in an environment variable for `RAILS_SERVE_STATIC_FILES` set to true as well incase someone accidentally brings that back in.

See: https://github.com/openshift/rails-ex/commit/881188e664287f84ebe6a0491127bd7e9df6b9bc#diff-1d98f0039bbc6df92adee882ed99d993 

Which was caused by the same careless config update: https://github.com/openshift/rails-ex/commit/c777e254dad3f34c15fcfd6f5f9ac1b39773afa0

**Pull request merged**
