### PR TITLE
make db service name a parameter

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik ptal but note that the rails example is currently failing for me (the blog welcome page shows up but the articles url hits a failure).  not sure what i'm missing and we seem to not output anything useful to stdout which is another thing we need to address....

**Comment by bparees** [comment]
@rhcarvalho ptal also.

**Comment by mfojtik** [comment]
@bparees warming up vagrant and going to test this

**Comment by bparees** [comment]
@mfojtik this is still not working for me as of tonight using straight master content, i'm getting:

Errno::EACCES: Permission denied - /opt/openshift/src/tmp/cache/assets/production/sprockets/v3.0/ULM2c_jFqHlAdAKkFkWJC-V3eLvDrGDdDBkJ34oI4pA.cache

wondering if the permission changes that were made in openshift have any bearing on this.

**Comment by bparees** [comment]
ls -l ULM2c_jFqHlAdAKkFkWJC-V3eLvDrGDdDBkJ34oI4pA.cache 
-rw-r--r--. 1 default default 36 Jun 16 04:35 ULM2c_jFqHlAdAKkFkWJC-V3eLvDrGDdDBkJ34oI4pA.cache

wonder if the issue is that we do asset compilation as the default user and then run as a different user?

**Comment by mfojtik** [comment]
@bparees i'm not getting this error (i'm using latest images and openshift master)...

**Comment by mfojtik** [comment]
``` console
I0616 13:04:21.698303       1 sti.go:388] ---> Starting asset compilation.
E0616 13:04:26.355850       1 sti.go:414] I, [2015-06-16T13:04:26.279313 #18664]  INFO -- : Writing /opt/openshift/src/public/assets/application-dfda1387e2621704c9c53ddd9c1573c1f5099fd3108a2a96d2b02d9b79203f15.js
E0616 13:04:26.360918       1 sti.go:414] I, [2015-06-16T13:04:26.279313 #18664]  INFO -- : Writing /opt/openshift/src/public/assets/application-dfda1387e2621704c9c53ddd9c1573c1f5099fd3108a2a96d2b02d9b79203f15.js
E0616 13:04:26.378039       1 sti.go:414] I, [2015-06-16T13:04:26.337283 #18664]  INFO -- : Writing /opt/openshift/src/public/assets/application-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css
E0616 13:04:26.396818       1 sti.go:414] I, [2015-06-16T13:04:26.337283 #18664]  INFO -- : Writing /opt/openshift/src/public/assets/application-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css
I0616 13:04:47.952421       1 sti.go:96] Using provided push secret for pushing openshift/ruby-20-centos7:latest image
I0616 13:04:47.953312       1 sti.go:99] Pushing 172.30.119.246:5000/test/rails-example image ..
```

**Comment by mfojtik** [comment]
LGTM (tested locally)

**Comment by mfojtik** [comment]
@bparees can you make one more change to the index.html? One step that is missing is to run the migration of database (which is not done now). So creating new articles doesn't work. To do so you have you execute following command:

``` console
oc exec -it -p <frontend-pod-name> -- bash -c 'RAILS_ENV=production bundle exec rake db:migrate'
```

**Comment by ewolinetz** [comment]
just as a thought... is there a way to add a lifecycle hook via oc?  this way we could migrate the db after a build automatically in case the users made any new db changes with their app

**Comment by bparees** [comment]
let's deal with DB migration as a follow on.  we should be doing it the same way we do it in django.

**Pull request merged**
